### ISSUE TITLE
License

### ISSUE THREAD

**Issue by michal-filip** [bali182/asyncapi-ws-to-ts#3]
Hi @bali182,

I would like to make async-related code generation part of our development workflow on an internal project. If we see that this is helpful but meet some hurdles, I'd be happy to contribute back (or publicly fork and enhance it). Would you mind adding a permissive license file to this repo? We haven't really evaluated it yet, but it looks very promising..
Thanks!

**Comment by bali182** [comment]
License has been added, sorry for the delay! I just picked MIT, is that suitable?

**Comment by michal-filip** [comment]
It sure is. Thanks!
